### ISSUE TITLE
Dependency on IdentityModel 4.4.0

### ISSUE THREAD

**Issue by hendrik-sqrsoftware-com** [MiXTelematics/MiX.Identity.Client#7]
We have not been able to use the Mix Integrate libraries from a .NET Core project.

The incompatibility seems to be related to the dependency of the Mix Library, specifically MiX.Identity.Client, on IdentityModel < 4.0.0.

Our .NET Core project relies on IdentityModel 4.4.0.

We have attempted placing the Mix dependent code in a separate assembly, both .NET Core and .NET Framework 4.6.2 but we persistently get the following exception when requesting positions:

Method not found: 'Void IdentityModel.Client.TokenClient..ctor(System.String, System.String, System.String, System.Net.Http.HttpMessageHandler, IdentityModel.Client.AuthenticationStyle)'.

Do you have sample code which shows how to overcome this, or are you planning a release that allows IdentityModel >= 4.0.0 in the near future?

**Comment by AlainH** [comment]
The issue you're seeing is the result of breaking changes to IdentityModel with the v4.0.0 release.

To address this, we're working on updating MiX.Identity.Client to eliminate the dependency entirely (no projected release date yet, I'm afraid)

News / updates will be posted here as / when they become available.

**Comment by alexander-bobrov** [comment]
Facing the same issue here. Hope it'll be solved soon :)

**Comment by GeorgeB2009** [comment]
Why not fork the code and upgrade it yourself? I have it running in .Net 7 without issues.

**Comment by alexander-bobrov** [comment]
> Why not fork the code and upgrade it yourself? I have it running in .Net 7 without issues.

Good point but I'm ready to wait for a while to get it fixed by maintainer.

**Comment by AlainH** [comment]
MiX.Identity.Client's dependency on IdentityModel has been eliminated - there should no longer be any issues using it in .NET Core
